# src/builder/library_record.py
"""
Structure records for the quantum-dot library.

Shared by the QD_builder library generator and the QDSpaceWebApp ingest so a
structure is described the same way whether it was generated by the builder
or added by hand: composition, centre species, size descriptors, a
rotation/translation-invariant fingerprint (to deduplicate and to match DFT
structures with their builder twins) and the record layout itself.
"""
from __future__ import annotations

import hashlib
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

import numpy as np
from numpy.typing import NDArray

SCHEMA_VERSION = 1
CENTRE_TOL = 0.5  # Å: an atom this close to the core centroid defines the centre


def read_xyz_first_frame(path: str) -> Tuple[List[str], NDArray[np.float64]]:
    """Symbols and coordinates of the first frame of an XYZ file."""
    with open(path) as fh:
        n = int(fh.readline().split()[0])
        fh.readline()
        symbols: List[str] = []
        coords: List[List[float]] = []
        for _ in range(n):
            parts = fh.readline().split()
            symbols.append(parts[0])
            coords.append([float(x) for x in parts[1:4]])
    return symbols, np.asarray(coords, float)


def composition(symbols: Iterable[str]) -> Dict[str, int]:
    comp: Dict[str, int] = {}
    for s in symbols:
        comp[s] = comp.get(s, 0) + 1
    return comp


def formula(comp: Dict[str, int], order: Sequence[str] = ()) -> str:
    """Formula string with `order` elements first (e.g. Cd, Se), then the rest alphabetically."""
    head = [e for e in order if comp.get(e)]
    tail = sorted(e for e in comp if e not in head)
    return "".join(f"{e}{comp[e]}" for e in head + tail)


def total_charge(comp: Dict[str, int], charges: Dict[str, float]) -> Optional[int]:
    """Formal total charge, or None when an element has no known charge."""
    if any(e not in charges for e in comp):
        return None
    return int(round(sum(float(charges[e]) * n for e, n in comp.items())))


def _core(symbols: Sequence[str], pts: NDArray[np.float64], native: Iterable[str]) -> NDArray[np.float64]:
    native = set(native)
    mask = np.array([s in native for s in symbols])
    return pts[mask] if mask.any() else pts


def centre_species(
    symbols: Sequence[str],
    pts: NDArray[np.float64],
    native: Iterable[str],
    tol: float = CENTRE_TOL,
) -> Tuple[str, float]:
    """
    Species of the native atom at the core centroid, or "interstitial" when
    no native atom lies within `tol`.  Returns (label, distance in Å).
    """
    native = set(native)
    idx = [i for i, s in enumerate(symbols) if s in native]
    if not idx:
        return "unknown", float("nan")
    core = pts[idx]
    d = np.linalg.norm(core - core.mean(axis=0), axis=1)
    k = int(np.argmin(d))
    label = symbols[idx[k]] if d[k] <= tol else "interstitial"
    return label, float(d[k])


def size_descriptors(
    symbols: Sequence[str],
    pts: NDArray[np.float64],
    native: Iterable[str],
) -> Dict[str, float]:
    """
    Core (native atoms only) size descriptors in nm.

    d_nm       equivalent-sphere diameter from the radius of gyration,
               2 * sqrt(5/3) * Rg: robust to shape and relaxation; the
               library's filter value.
    d_max_nm   largest centroid distance, doubled.
    d_hull_nm  diameter of the sphere with the core convex-hull volume.
    """
    core = _core(symbols, pts, native)
    out = {"n_core": int(len(core))}
    if len(core) < 2:
        return {**out, "d_nm": 0.0, "d_max_nm": 0.0, "d_hull_nm": 0.0}
    cen = core.mean(axis=0)
    r = np.linalg.norm(core - cen, axis=1)
    rg = float(np.sqrt(np.mean(r ** 2)))
    out["d_nm"] = round(2.0 * np.sqrt(5.0 / 3.0) * rg / 10.0, 3)
    out["d_max_nm"] = round(2.0 * float(r.max()) / 10.0, 3)
    try:
        from scipy.spatial import ConvexHull
        vol = ConvexHull(core).volume
        out["d_hull_nm"] = round(2.0 * (3.0 * vol / (4.0 * np.pi)) ** (1.0 / 3.0) / 10.0, 3)
    except Exception:
        out["d_hull_nm"] = None
    return out


def fingerprint(symbols: Sequence[str], pts: NDArray[np.float64], resolution: float = 0.05) -> str:
    """
    Rotation- and translation-invariant structure hash: composition plus the
    per-species sorted distances to the centroid, binned to `resolution` Å.
    Identical builder outputs (e.g. two sizes producing the same cluster)
    share a fingerprint; relaxed geometries generally do not.
    """
    pts = np.asarray(pts, float)
    cen = pts.mean(axis=0)
    parts = []
    for s in sorted(set(symbols)):
        d = np.linalg.norm(pts[[i for i, x in enumerate(symbols) if x == s]] - cen, axis=1)
        bins = np.round(np.sort(d) / resolution).astype(int)
        parts.append(s + ":" + ",".join(map(str, bins)))
    return hashlib.sha1("|".join(parts).encode()).hexdigest()[:16]


def radial_signature(symbols: Sequence[str], pts: NDArray[np.float64]) -> Dict[str, NDArray[np.float64]]:
    """Per-species sorted distances to the centroid (rotation/translation invariant)."""
    pts = np.asarray(pts, float)
    cen = pts.mean(axis=0)
    return {
        s: np.sort(np.linalg.norm(pts[[i for i, x in enumerate(symbols) if x == s]] - cen, axis=1))
        for s in sorted(set(symbols))
    }


def signature_distance(a: Dict[str, NDArray[np.float64]], b: Dict[str, NDArray[np.float64]]) -> float:
    """
    Mean absolute difference (Å) between two radial signatures; infinite when
    the compositions differ.  Tolerant to small perturbations or relaxation,
    unlike `fingerprint`: used to link a DFT structure to its builder twin.
    """
    if set(a) != set(b) or any(len(a[s]) != len(b[s]) for s in a):
        return float("inf")
    diffs = np.concatenate([np.abs(a[s] - b[s]) for s in a])
    return float(diffs.mean()) if len(diffs) else 0.0


def min_distance(pts: NDArray[np.float64]) -> float:
    from scipy.spatial import cKDTree
    if len(pts) < 2:
        return float("inf")
    d, _ = cKDTree(pts).query(pts, k=2)
    return float(d[:, 1].min())


def structure_id(material: str, centre: str, formula_str: str, surface: str) -> str:
    return f"{material}-{centre}-{formula_str}-{surface}"


def describe_structure(
    symbols: Sequence[str],
    pts: NDArray[np.float64],
    *,
    native_order: Sequence[str],
    charges: Dict[str, float],
) -> dict:
    """Everything computable from coordinates alone (the core of a record)."""
    comp = composition(symbols)
    native = set(native_order)
    centre, centre_d = centre_species(symbols, pts, native)
    return {
        "formula": formula(comp, native_order),
        "composition": comp,
        "core": {e: n for e, n in comp.items() if e in native},
        "ligands": {e: n for e, n in comp.items() if e not in native},
        "n_atoms": int(len(symbols)),
        "total_charge": total_charge(comp, charges),
        "centre": centre,
        "centre_offset_A": round(centre_d, 3),
        "size": size_descriptors(symbols, pts, native),
        "fingerprint": fingerprint(symbols, pts),
    }


def make_record(
    *,
    material: str,
    family: str,
    phase: str,
    surface: str,
    source: str,
    description: dict,
    stages: List[dict],
    origin: Optional[dict] = None,
    extra: Optional[dict] = None,
) -> dict:
    """Assemble a library record (schema_version 1)."""
    rec = {
        "schema_version": SCHEMA_VERSION,
        "id": structure_id(material, description["centre"], description["formula"], surface),
        "material": material,
        "family": family,
        "phase": phase,
        "surface": surface,
        "source": source,
        **description,
        "stages": stages,
        "origin": origin or {},
    }
    if extra:
        rec.update(extra)
    return rec
